# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41a0d1cd99c33936644940b5bf89298437a6118b4e25d4794dfea4eb57efe72ee460149d572a161aee0b4ff07538a446e98a419a1638232a25144891bf45a299

test:
  secret_key_base: 620f314abafd18e903356f862100242a84f2e667239ecd9464c7042a521b3a4b58b13c35b414f43e9a40decd14fa41c7abca88c6b801483037e2fa73e6fb9040

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
